### ISSUE TITLE
Cannot infer type after 0.2.4 release

### ISSUE THREAD

**Issue by dten** [Valloric/hamcrest2-rust#7]
```
43
    |
174 |             assert_that!(b.as_slice(), is(equal_to(&[1.0, 1.0, 1.0])));
    |             ------------------------------^^^^^^^^---------------------
    |             |                             |
    |             |                             cannot infer type for `D`
    |             consider giving `m` a type
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

**Comment by dten** [comment]
`b.as_slice()` returns `&[f64]`

**Comment by Valloric** [comment]
Could you provide a little bit more info? A small, compilable test case would be most welcome. :)

**Comment by Valloric** [comment]
OK, I can repro this with the following new test in `tests/equal_to.rs`. Passes on 0.2.3, fails to compile on 0.2.4.

```rust
  #[test]
  fn equality_of_floats_slice() {
    let slice = [1.0, 2.0, 3.0];
    assert_that!(&slice, eq(&[1.0, 2.0, 3.0]));
  }
```

error:
```
error[E0282]: type annotations needed
  --> tests/equal_to.rs:55:26
   |
55 |     assert_that!(&slice, eq(&[1.0, 2.0, 3.0]));
   |     ---------------------^^--------------------
   |     |                    |
   |     |                    cannot infer type for `D`
   |     consider giving `m` a type
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

@Gerschtli Thoughts?

**Comment by Gerschtli** [comment]
The indirection through the `Borrow` trait is the problem. Without this rust is able to infer the type..

Would be solved with following additions:
```rust
pub struct EqualToSlice<'a, T, D> {
  expected: &'a [T],
  marker: PhantomData<D>,
}

impl<'a, T, D> fmt::Display for EqualToSlice<'a, T, D>
where
  T: fmt::Debug,
{
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    fmt::Debug::fmt(self.expected, f)
  }
}

impl<'a, T, D, B> Matcher<B> for EqualToSlice<'a, T, D>
where
  [T]: PartialEq<[D]>,
  T: fmt::Debug,
  D: fmt::Debug,
  B: Borrow<[D]>,
{
  fn matches(&self, actual: B) -> MatchResult {
    if self.expected.eq(actual.borrow()) {
      success()
    } else {
      Err(format!("was {:?}", actual.borrow()))
    }
  }
}

pub fn equal_to<'a, T, D, V>(expected: &'a [T]) -> EqualToSlice<T, D> {
  EqualToSlice {
    expected,
    marker: PhantomData,
  }
}
```

The problem is, I have no idea how to merge these two functions together to provide a nice API:
```rust
pub fn equal_to<'a, T, D, V>(expected: &'a [T]) -> EqualToSlice<T, D> {
  EqualToSlice {
    expected,
    marker: PhantomData,
  }
}

pub fn equal_to<T, D>(expected: T) -> EqualTo<T, D> {
  EqualTo {
    expected,
    marker: PhantomData,
  }
}
```

**Comment by Valloric** [comment]
@Gerschtli Hm... maybe ask on #rust IRC channel? If the folks there can't figure it out, no one can...

**Comment by Gerschtli** [comment]
Oh, I'm very sorry! I completely forgot about this issue..

BTW found another problem:
```rust
assert_that!("", is(equal_to(""))); // -> fails
```

I will try to work out a fix.

**Comment by dten** [comment]
Great thanks 😁

**Comment by Valloric** [comment]
Released 0.2.6 with fix. Sorry for the breakage!
